let g:NERDTreeHighlightCursorline = 1
let g:NERDTreeShowHidden = 1
let g:NERDTreeStatusline = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeMinimalMenu = 0
let g:NERDTreeIgnore=['\node_modules$', '\.git$']
let g:NERDTreeQuitOnOpen = 1
let g:NERDTreeShowBookmarks = 1
let g:NERDTreeAutoCenter = 1
let g:NERDTreeCaseSensitiveSort = 1
let g:NERDTreeHijackNetrw = 1
let g:NERDTreeShowBookmarks = 1
