require('general')
require('telescope-config')
require('tabline')
require('statusline')
require('ui')
require('vim-js')
require('treesitter')
require('lsp')
require('project-nvim')
vim.cmd('source ~/.config/nvim/lua/general/term.vim')
