require('auto-completion')
require('general.packer')
require('general.settings')
require('general.mapping')
require('general.autocommands')
require('telescope-config')
require('tabline')
require('statusline')
require('ui')
require('vim-js')
require('treesitter')
require('lsp-config')
vim.cmd('source ~/.config/nvim/lua/auto-completion/cmpe.vim')
