require("afnan.plugins")
require("afnan.dashboard")
require("afnan.settings")
require("afnan.mapping")
require("afnan.disabled")
vim.cmd("source ~/.config/nvim/lua/afnan/autocommands.vim")
require("afnan.luasnips")
