require('afnan.plugins')
require('afnan.settings')
require('afnan.mapping')
require('afnan.disabled')
vim.cmd('source ~/.config/nvim/lua/afnan/autocommands.vim')
vim.cmd('source ~/.config/nvim/lua/afnan/colors.vim')
require('afnan.telescope')
require('afnan.notifications')
require('afnan.tabline')
require('afnan.lsp')
