require("general.mapping")
require("general.settings")
require("general.packer")
require("general.disabled")
vim.cmd("source ~/.config/nvim/lua/general/autocommands.vim")
vim.cmd("source ~/.config/nvim/lua/general/term.vim")
