local icons = {
  rounded_left_filled = '',
  rounded_right_filled = '',
  arrow_left_filled = '',
  arrow_right_filled = '',
  arrow_left = '',
  arrow_right = '',
  ghost = '',
  warn = '',
  info = '',
  error = '',
  hint = '',
  branch = '',
  file = '',
  dotdotdot = '…',
  information = '',
  symlink = '',
  line_number = '',
  git = {
    unstaged = '✗',
    staged = '✓',
    unmerged = '',
    renamed = '➜',
    untracked = '★',
    deleted = '',
    ignored = '◌',
  },
  folder = {
    arrow_open = '',
    arrow_closed = '',
    default = '',
    open = '',
    empty = '',
    empty_open = '',
    symlink = '',
    symlink_open = '',
  },
}

return icons
