require("ui.dashboard")
require("ui.statusline")
require("ui.sessions")
require("ui.nerdtree")
vim.cmd("source ~/.config/nvim/lua/ui/colors.vim")
require("ui.treesitter")
require("ui.tabline")
require("ui.git-signs")
require("ui.toggleterm")
