require("ui.dashboard")
require("ui.statusline")
vim.cmd("source ~/.config/nvim/lua/ui/nerdtree.vim")
require("ui.treesitter")
require("ui.tabline")
require("ui.git-signs")
require("ui.neoscroll")
require("ui.rich-presence")
