name: Linting and Formatting
on: push

jobs: 
  stylua:
    name: "Formatting check with Stylua"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Linting with stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
  luacheck:
    name: "Linting with Luacheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4

      - name: Use luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck *.lua lua/*
