name: Lint

on: push

jobs: 
  luacheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install lua and luarocks
      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck --config=".luacheckrc" *.lua lua/*
